apiVersion: apps/v1
kind: Deployment
metadata:
  name: classroom-client-shiri
  namespace: team-smartbase
  labels:
    env: development
    project: handover
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classroom-client-shiri
  template:
    metadata:
      labels:
        app: classroom-client-shiri
        env: development
        project: handover
    spec:
      securityContext:
        fsGroup: 101
        runAsGroup: 101
        runAsNonRoot: true
        runAsUser: 101
      volumes:
        - emptyDir: {}
          name: cache
        - emptyDir: {}
          name: run
        - emptyDir: {}
          name: log
      containers:
        - name: classroom-client-container-shiri
          image: ghcr.io/shirialoni/classroom-client
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 499Mi
            requests:
              cpu: 250m
              memory: 249Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: cache
            - mountPath: /var/run
              name: run
            - mountPath: /var/log/nginx
              name: log
