apiVersion: v1
kind: Service
metadata:
  name: classroom-client
  namespace: team-smartbase
  labels:
    env: development
    project: classroom-client-service
spec:
  selector:
    app: classroom-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: ClusterIP
