apiVersion: v1
kind: Service
metadata:
  name: classroom-server
  namespace: team-smartbase
  labels:
    env: development
    project: classroom-server-service
spec:
  selector:
    app: classroom-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP